apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deploy 
  namespace: nginx-ns 
spec: 
  replicas: 2
  selector: 
    matchLabeles:
      name: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec: 
      containers:
      - name: nginx 
        image: nginx:latest 
        ports:
        - containerPort: 80 

     
    

  