apiVersion: batch/v1
kind: Job 
metadata: 
  name: demo-job
  namespace: nginx-ns 
spec: 
  completions: 1
  parallelism: 1
  template: 
    metadata: 
      name: demo-job-pod 
      labels: 
        app: batch-task 
    spec: 
      containers: 
      - name: batch-container 
        image: busybox:latest 
        command: ["sh", "-c", echo "hello This is demo for Job && sleep 10"]   
      restartPolicy: Never 
