apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: local-pv
  namespace: nginx-ns
  labels:
    app: local 
spec: 
  capacity:
    storage: 2Gi 
  accessModes:
  - ReadWriteOnce 
  storageClassName: local-storage
  hostPath: 
    path: C:\Users\Sushant\Documents\YAML-files