apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: local-pvc
  namespace: nginx-ns 
  labels: 
    app: local-pvc 
spec:
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 2Gi 
  storageClassName: local-storage