apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deploy 
  namespace: nginx-ns 
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
      - name: nginx 
        image: nginx:latest 
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-pv 
      volumes: 
        - name: nginx-pv
          persistentVolumeClaim: 
            claimName: local-pvc
