apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 # Number of Pods to create
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 # Port exposed by the container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort # Change to ClusterIP or LoadBalancer if needed
  ports:
  - port: 80         # Port exposed by the service
    targetPort: 80   # Port the Pod listens on
    nodePort: 30080  # NodePort (optional, only for NodePort type)

